Changes required to get IppDotNetDevKitCSV3 compiling on a machine with VS 2022.
Avoiding the error, "error CS0041: Unexpected error writing debug information -- 'Unable to load DLL 'Microsoft.DiaSymReader.Native.amd64.dll'"